<?php

namespace Elements;

class ElementsException extends \Exception {

	const SVC_INVALID_OWNERSHIP										= 10001;
	const SVC_MISMATCHING_PARAMETERS								= 10002;
	const SVC_ILLEGAL_PROPERTY										= 10003;
	const SVC_KEY_GENERATION										= 10004;
	const SVC_VALIDATION_EXCEPTION									= 10005;
	const AUTH_CHALLENGE_EXPIRED									= 20001;
	const AUTH_INVALID_CHALLENGE									= 20002;
	const AUTH_INVALID_PASSWORD										= 20003;
	const AUTH_INVALID_TICKET										= 20004;
	const AUTH_INVALID_REALM										= 20005;
	const AUTH_INVALID_TICKET_VERSION								= 20006;
	const AUTH_REALM_NOT_FOUND										= 20007;
	const AUTH_TICKET_EXPIRED										= 20008;
	const AUTH_TICKET_REVOKED										= 20009;
	const AUTH_NAMED_PARTY_NOT_FOUND								= 20010;
	const AUTH_CREDENTIAL_MISMATCH									= 20011;
	const AUTH_CREDENTIAL_NOT_FOUND									= 20012;
	const AUTH_PERMISSION_DENIED									= 20013;
	const AUTH_PERMISSION_SCOPE										= 20014;
	const AUTH_APPLICATION_FAMILY_PERMISSION						= 20015;
	const AUTH_APPLICATION_PERMISSION								= 200016;
	const AUTH_ROLE_ASSIGNMENT_NOT_FOUND_EXCEPTION 					= 200017;
	const CAT_CATALOG_VERSION_NOT_FOUND								= 40001;
	const CAT_ITEM_NOT_FOUND										= 40002;
	const CAT_ITEM_INSTANCE_NOT_FOUND								= 40003;
	const CAT_INVALID_ITEM_OWNERSHIP								= 40004;
	const CAT_ITEM_TYPE_NOT_FOUND									= 40005;
	const CAT_ITEM_GROUP_NOT_FOUND									= 40006;
	const CAT_ITEM_INSTANCE_GROUP_NOT_FOUND							= 40007;
	const CAT_ITEM_MISTMATCH										= 40008;
	const CAT_RECURSIVE_ITEM_GROUP									= 40009;
	const CAT_RECURSIVE_ITEM_INSTANCE_GROUP							= 40010;
	const CAT_ITEM_EXPIRED											= 40011;
	const CAT_CANNOT_SET_EXPIRATION_INTO_PAST						= 40012;
	const CAT_ITEM_DETAIL_NOT_FOUND									= 40013;
	const CAT_ITEM_DETAIL_L10_N_NOT_FOUND							= 40014;
	const CAT_ITEM_TYPE_L10_N_NOT_FOUND								= 40015;
	const CAT_ITEM_L10_N_NOT_FOUND									= 40016;
	const CAT_AGE_RATING_NOT_FOUND									= 40017;
	const CAT_AGE_RATING_L10_N_NOT_FOUND							= 40018;
	const CAT_ITEM_CATEGORY_NOT_FOUND								= 40019;
	const CAT_ITEM_DETAIL_ID_IMMUTABLE								= 40020;
	const CAT_ITEM_MULTI_VALUED_ATTRIBUTE_NOT_FOUND					= 40021;
	const CAT_PHYSICAL_GOOD_ILLEGAL_STATE							= 40022;
	const CAT_CANNOT_TRANSFER_PHYSICAL_GOOD							= 40023;
	const CAT_ITEM_NOT_ASSIGNED_TO_ITEM_GROUP						= 40024;
	const OFFER_NOT_FOUND											= 80001;
	const OFFER_INVALID_OFFER_PRICE_ENTRY							= 80002;
	const OFFER_NOT_CONSUMABLE										= 80003;
	const OFFER_REQUIREMENTS_NOT_SATISFIED							= 80004;
	const OFFER_UNAVAILABLE_OFFER									= 80005;
	const OFFER_UNSUPPORTED_OFFER									= 80006;
	const USER_NOT_FOUND											= 130001;
	const USER_PROFILE_NOT_FOUND									= 130002;
	const USER_INVALID_USER											= 130003;
	const USER_NOT_SIGNED_IN										= 130004;
	const USER_LOGIN_NOT_FOUND										= 130005;
	const USER_ANONYMOUS_USER										= 130006;
	const USER_BLOCKED												= 130007;
	const USER_NOT_ENABLED											= 130008;
	const USER_CHILD_RESTRICTION									= 130009;
	const USER_AGE_RATING											= 130010;
	const INVENTORY_NO_INVENTORY_ENTRY								= 190001;
	const INVENTORY_OVER_CONSUMPTION								= 190002;
	const INVENTORY_UNDER_RESERVED									= 190003;
	const INVENTORY_DELETE_FAILED_ITEM_INSTANCE_EXISTS				= 190004;
	const MARKET_VOUCHER_PURCHASE									= 210001;
	const MARKET_INVALID_VOUCHER_PRICE								= 210002;
	const MARKET_FUND_REQUEST										= 210003;
	const MARKET_PURCHASE_ORDER_NOT_FOUND							= 210004;
	const MARKET_PURCHASE_ORDER_NOT_REFUNDABLE						= 210005;
	const MARKET_PURCHASE_ORDER_REFUND								= 210006;
	const MARKET_FOREX_OFFER_NOT_FOUND								= 210007;
	const MARKET_COUNTER_CURRENCY_MISSING							= 210008;
	const MARKET_VIRTUAL_COUNTER_CURRENCY							= 210009;
	const MARKET_INVALID_FOREX_OFFER								= 210010;
	const MARKET_COUNTER_CURRENCY_MISMATCH							= 210011;
	const MARKET_UNEXPECTED_PAYMENT									= 210012;
	const MARKET_UNEXPECTED_PAYMENT_GATEWAY_CONFIG					= 210013;
	const MARKET_PAYMENT_GATEWAY_CONFIG_CURRENCY_MISMATCH			= 210014;
	const MARKET_BUYER_ACCOUNT_MISSING								= 210015;
	const MARKET_UNEXPECTED_BUYER									= 2100016;
	const MARKET_BASE_CURRENCY_MIS_MATCH							= 2100017;
	const MARKET_UNABLE_TO_FINISH_PURCHASE							= 2100018;
	const MARKET_OFFER_CURRENCY_MISMATCH							= 210019;
	const MARKET_PAYMENT_CURRENCY_INCORRECT							= 2100020;
	const MARKET_RECURRING_PAYMENT_NOT_ALLOWED						= 2100021;
	const MARKET_PO_ALREADY_REFUNDED								= 2100022;
	const MARKET_INVALID_AUTHORIZATION								= 2100023;
	const CURRENCY_NOT_FOUND										= 220001;
	const CURRENCY_INVALID_CURRENCY									= 220002;
	const CURRENCY_CANNOT_CREATE_OR_MODIFY_REAL_CURRENCIES			= 220003;
	const APPMGR_CURRENCY_NOT_VISIBLE								= 230001;
	const APPMGR_APPLICATION_FAMILY_NOT_FOUND						= 230002;
	const APPMGR_APPLICATION_FAMILY_MISMATCH						= 230003;
	const APPMGR_APPLICATION_NOT_FOUND								= 230004;
	const APPMGR_APPLICATION_MISMATCH								= 230005;
	const APPMGR_APPLICATION_CHANGE									= 230006;
	const APPMGR_APPLICATION_FAMILY_CHANGE							= 230007;
	const EVENT_GROUP_NOT_SET										= 240001;
	const EVENT_GROUP_NOT_FOUND										= 240002;
	const EVENT_GROUP_DUPLICATE_EXTERNAL_TRANSACTION_ID				= 240003;
	const VOUCHER_EXPIRED_VOUCHER									= 250001;
	const VOUCHER_NOT_FOUND											= 250002;
	const VOUCHER_POLICY_NOT_FOUND									= 250003;
	const VOUCHER_STATE_CHANGE										= 250004;
	const VOUCHER_NOT_EFFECTIVE										= 250005;
	const ITEM_VOUCHER_MULTIPLE_REDEMPTIONS_PER_USER				= 260001;
	const ITEM_VOUCHER_CURRENCY_MISMATCH							= 260002;
	const ITEM_VOUCHER_TEMPLATE_NOT_FOUND							= 260003;
	const ITEM_VOUCHER_TEMPLATE_NOT_AVAILABLE						= 260004;
	const MIDAS_ACCOUNT_NOT_FOUND									= 270001;
	const MIDAS_ACCOUNT_POLICY_NOT_FOUND							= 270002;
	const MIDAS_ACCOUNT_NOT_ACTIVE									= 270003;
	const MIDAS_ACCOUNT_NOT_COMPATIBLE								= 270004;
	const MIDAS_ACCOUNT_POLICY_VIOLATION							= 270005;
	const MIDAS_ACCOUNT_MAX_BALANCE_EXCEEDED						= 270006;
	const MIDAS_ACCOUNT_MIN_BALANCE_EXCEEDED						= 270007;
	const MIDAS_ACCOUNT_WITHDRAW_FROM_SINK							= 270008;
	const MIDAS_ACCOUNT_DEPOSIT_TO_SOURCE							= 270009;
	const MIDAS_ACCOUNT_ROLE_NOT_COMPATIBLE							= 270010;
	const MIDAS_ACCOUNT_INSUFFICIENT_BALANCE						= 270011;
	const MIDAS_ACCOUNT_INVALID_AMOUNT								= 270012;
	const MIDAS_ACCOUNT_INVALID_CHARGE								= 270013;
	const MIDAS_ACCOUNT_MIDAS_TXN_NOT_FOUND							= 270014;
	const MIDAS_ACCOUNT_NEGATIVE_TRANSFER_AMOUNT					= 270015;
	const MIDAS_ACCOUNT_NOT_VIRTUAL_MINT							= 2700016;
	const MIDAS_ACCOUNT_TRANSFER									= 2700017;
	const MIDAS_ACCOUNT_ZERO_TRANSFER_AMOUNT						= 2700018;
	const MIDAS_PAYMENT_UNSUPPORTED_PAYMENT							= 280001;
	const MIDAS_PAYMENT_PURCHASE_ORDER_NOT_FOUND					= 280006;	
	const FOREX_BADLY_DATED_FOREX_OFFER								= 290001;
	const FOREX_OFFER_NOT_FOUND										= 290002;
	const FOREX_INVALID_PREFERRED_AMOUNTS							= 290003;
	const PAYMENT_GATEWAY_CONFIG_NOT_FOUND							= 300001;
	const PAYMENT_GATEWAY_NOT_FOUND									= 310001;
	const PAYMENT_GATEWAY_INVALID_PAYMENT_GATEWAY_OPERATION			= 310002;
	const PAYMENT_GATEWAY_INVALID_PAYMENT_GATEWAY_CURRENCY			= 310003;
	const PAYMENT_PROCESSOR											= 320001;
	const PAYMENT_PROCESSOR_PAYMENT_OPTION_NOT_ENABLED_FOR_ACCOUNT 	= 320002;
	const PAYMENT_PROCESSOR_UNAVAILABLE								= 320003;
	const PAYMENT_PROCESSOR_UNSUPPORTED_CURRENCY					= 320004;
	const PAYMENT_PROCESSOR_UNSUPPORTED_PAYMENT_OPTION				= 320005;
	const PAYMENT_PROCESSOR_CURRENCY_NOT_ENABLED_FOR_ACCOUNT		= 320006;
	const CURRENCY_EXCHANGE											= 330001;
	const RESTRICTION_LIMIT_REACHED_USER_BLOCKED					= 340001;
	const RESTRICTION_LIMIT_REACHED_ACTION_REJECTED					= 340002;
	const POLICY_NOT_FOUND											= 350001;
	const POLICY_COLLECTION_NOT_FOUND								= 350002;
	const POLICY_COLLECTION_INCLUSIVENESS							= 350003;
	const RECOMMENDATION_STATIC_RECOMMENDATION_NOT_FOUND			= 360001;
	const PROMOTION_NOT_FOUND										= 370001;
	const PROMOTION_VALIDATION										= 370002;
	const PROMOTION_CANNOT_BE_COMBINED								= 370003;
	const PROMOTION_NOT_COMPATIBLE_WITH_OFFER						= 370004;
	const PROMOTION_WILL_CAUSE_OFFER_GO_UNDER_MIN_PRICE	 			= 370005;
	const PROMOTION_REQUIREMENT_NOT_SATISFIED						= 370006;
	const PROMOTION_JOB_NOT_FOUND									= 370007;
	const PROMOTION_JOB_VALIDATION									= 370008;
	const PROMOTION_EXPIRED											= 370009;
	const PROMOTION_EXCEEDS_MAX_USES								= 370010;
	const PROMOTION_USER_EXCEEDS_MAX_PROMOTION_USES					= 370011;
	const PROMOTION_INELIGIBLE_USER									= 370012;
	const PROMOTION_NOT_YET_EFFECTIVE								= 370013;
	const PROMOTION_INVALID_PROMOTION_STATE							= 370014;
	const ORGANIC_TFEL_TFE_INVALID_LOGIN_INFO						= 990001;
	const ORGANIC_TFEL_TFE_ILLEGAL_ARGUMENT							= 990002;
	const ORGANIC_TFEL_TFE_NAMED_PARTY_NOT_FOUND					= 990003;
	const ORGANIC_TFEL_TFE_ACCOUNT_NOT_FOUND						= 990004;
	const ORGANIC_TFEL_TFE_SERVICE									= 990005;
	const ORGANIC_TFEL_TFE_APPLICATION_PROFILE_NOT_FOUND			= 990006;
	const ORGANIC_TFEL_TFE_OFFER_TYPE_MISMATCH						= 990007;
	const ORGANIC_TFEL_TFE_WSDL_NOT_FOUND							= 990008;
	const ORGANIC_TFEL_TFE_ENTITY_EXISTS							= 990009;
	const ORGANIC_TFEL_TFE_NOT_A_TWOFISH							= 990010;
	const ORGANIC_TFEL_TFE_ROLLBACK									= 990011;
	const ORGANIC_TFEL_TFE_ACTOR_NOT_FOUND							= 990012;
	const ORGANIC_TFEL_TFE_ENTITY_NOT_FOUND							= 990013;
	const ORGANIC_TFEL_TFE_BATCH_TIMEOUT							= 990014;
	const ORGANIC_TFEL_TFE_USER_BLOCKED								= 990015;



	protected $messages = array(
		self::SVC_INVALID_OWNERSHIP										=> "Invalid Ownership",
		self::SVC_MISMATCHING_PARAMETERS								=> "Mismatching Parameters",
		self::SVC_ILLEGAL_PROPERTY										=> "Illegal Property",
		self::SVC_KEY_GENERATION										=> "Key Generation",
		self::SVC_VALIDATION_EXCEPTION									=> "Validation Exception",
		self::AUTH_CHALLENGE_EXPIRED									=> "Challenge Expired",
		self::AUTH_INVALID_CHALLENGE									=> "Invalid Challenge",	
		self::AUTH_INVALID_PASSWORD										=> "Invalid Password",	
		self::AUTH_INVALID_TICKET										=> "Invalid Ticket",	
		self::AUTH_INVALID_REALM										=> "Invalid Realm",
		self::AUTH_INVALID_TICKET_VERSION								=> "Invalid Ticket Version",
		self::AUTH_REALM_NOT_FOUND										=> "Realm Not Found",	
		self::AUTH_TICKET_EXPIRED										=> "Ticket Expired",	
		self::AUTH_TICKET_REVOKED										=> "Ticket Revoked",	
		self::AUTH_NAMED_PARTY_NOT_FOUND								=> "Named Party Not Found",
		self::AUTH_CREDENTIAL_MISMATCH									=> "Credential Mismatch",
		self::AUTH_CREDENTIAL_NOT_FOUND									=> "Credential Not Found",
		self::AUTH_PERMISSION_DENIED									=> "Permission Denied",	
		self::AUTH_PERMISSION_SCOPE										=> "Permission Scope",	
		self::AUTH_APPLICATION_FAMILY_PERMISSION						=> "Application Family Permission",	
		self::AUTH_APPLICATION_PERMISSION								=> "Application Permission",
		self::AUTH_ROLE_ASSIGNMENT_NOT_FOUND_EXCEPTION 					=> "Role Assignment Not Found Exception", 			
		self::CAT_CATALOG_VERSION_NOT_FOUND								=> "Catalog Version Not Found",
		self::CAT_ITEM_NOT_FOUND										=> "Item Not Found",	
		self::CAT_ITEM_INSTANCE_NOT_FOUND								=> "Item Instance Not Found",
		self::CAT_INVALID_ITEM_OWNERSHIP								=> "Invalid Item Ownership",
		self::CAT_ITEM_TYPE_NOT_FOUND									=> "Item Type Not Found",
		self::CAT_ITEM_GROUP_NOT_FOUND									=> "Item Group Not Found",
		self::CAT_ITEM_INSTANCE_GROUP_NOT_FOUND							=> "Item Instance Group Not Found",	
		self::CAT_ITEM_MISTMATCH										=> "Item Mistmatch",	
		self::CAT_RECURSIVE_ITEM_GROUP									=> "Recursive Item Group",
		self::CAT_RECURSIVE_ITEM_INSTANCE_GROUP							=> "Recursive Item Instance Group",	
		self::CAT_ITEM_EXPIRED											=> "Item Expired",
		self::CAT_CANNOT_SET_EXPIRATION_INTO_PAST						=> "Cannot Set Expiration Into Past",
		self::CAT_ITEM_DETAIL_NOT_FOUND									=> "Item Detail Not Found",
		self::CAT_ITEM_DETAIL_L10_N_NOT_FOUND							=> "Item Detail L10 N Not Found",	
		self::CAT_ITEM_TYPE_L10_N_NOT_FOUND								=> "Item Type L10 N Not Found",
		self::CAT_ITEM_L10_N_NOT_FOUND									=> "Item L10 N Not Found",
		self::CAT_AGE_RATING_NOT_FOUND									=> "Age Rating Not Found",
		self::CAT_AGE_RATING_L10_N_NOT_FOUND							=> "Age Rating L10 N Not Found",
		self::CAT_ITEM_CATEGORY_NOT_FOUND								=> "Item Category Not Found",
		self::CAT_ITEM_DETAIL_ID_IMMUTABLE								=> "Item Detail Id Immutable",
		self::CAT_ITEM_MULTI_VALUED_ATTRIBUTE_NOT_FOUND					=> "Item Multi Valued Attribute Not Found",	
		self::CAT_PHYSICAL_GOOD_ILLEGAL_STATE							=> "Physical Good Illegal State",	
		self::CAT_CANNOT_TRANSFER_PHYSICAL_GOOD							=> "Cannot Transfer Physical Good",	
		self::CAT_ITEM_NOT_ASSIGNED_TO_ITEM_GROUP						=> "Item Not Assigned To Item Group",
		self::OFFER_NOT_FOUND											=> "Offer Not Found",	
		self::OFFER_INVALID_OFFER_PRICE_ENTRY							=> "Invalid Offer Price Entry",
		self::OFFER_NOT_CONSUMABLE										=> "Offer Not Consumable",
		self::OFFER_REQUIREMENTS_NOT_SATISFIED							=> "Offer Requirements Not Satisfied",
		self::OFFER_UNAVAILABLE_OFFER									=> "Unavailable Offer",	
		self::OFFER_UNSUPPORTED_OFFER									=> "Unsupported Offer",	
		self::USER_NOT_FOUND											=> "User Not Found",
		self::USER_PROFILE_NOT_FOUND									=> "Profile Not Found",	
		self::USER_INVALID_USER											=> "Invalid User",
		self::USER_NOT_SIGNED_IN										=> "User Not Signed In",
		self::USER_LOGIN_NOT_FOUND										=> "Login Not Found",	
		self::USER_ANONYMOUS_USER										=> "Anonymous User",
		self::USER_BLOCKED												=> "User Blocked",
		self::USER_NOT_ENABLED											=> "User Not Enabled",	
		self::USER_CHILD_RESTRICTION									=> "Child Restriction",	
		self::USER_AGE_RATING											=> "Age Rating",
		self::INVENTORY_NO_INVENTORY_ENTRY								=> "No Inventory Entry",
		self::INVENTORY_OVER_CONSUMPTION								=> "Over Consumption",	
		self::INVENTORY_UNDER_RESERVED									=> "Under Reserved",	
		self::INVENTORY_DELETE_FAILED_ITEM_INSTANCE_EXISTS				=> "Delete Failed Item Instance Exists",
		self::MARKET_VOUCHER_PURCHASE									=> "Voucher Purchase",	
		self::MARKET_INVALID_VOUCHER_PRICE								=> "Invalid Voucher Price",
		self::MARKET_FUND_REQUEST										=> "Fund Request",
		self::MARKET_PURCHASE_ORDER_NOT_FOUND							=> "Purchase Order Not Found",
		self::MARKET_PURCHASE_ORDER_NOT_REFUNDABLE						=> "Purchase Order Not Refundable",	
		self::MARKET_PURCHASE_ORDER_REFUND								=> "Purchase Order Refund",
		self::MARKET_FOREX_OFFER_NOT_FOUND								=> "Forex Offer Not Found",
		self::MARKET_COUNTER_CURRENCY_MISSING							=> "Counter Currency Missing",
		self::MARKET_VIRTUAL_COUNTER_CURRENCY							=> "Virtual Counter Currency",
		self::MARKET_INVALID_FOREX_OFFER								=> "Invalid Forex Offer",
		self::MARKET_COUNTER_CURRENCY_MISMATCH							=> "Counter Currency Mismatch",
		self::MARKET_UNEXPECTED_PAYMENT									=> "Unexpected Payment",
		self::MARKET_UNEXPECTED_PAYMENT_GATEWAY_CONFIG					=> "Unexpected Payment Gateway Config",
		self::MARKET_PAYMENT_GATEWAY_CONFIG_CURRENCY_MISMATCH			=> "Payment Gateway Config Currency Mismatch",
		self::MARKET_BUYER_ACCOUNT_MISSING								=> "Buyer Account Missing",
		self::MARKET_UNEXPECTED_BUYER									=> "Unexpected Buyer",	
		self::MARKET_BASE_CURRENCY_MIS_MATCH							=> "Base Currency Mis Match",
		self::MARKET_UNABLE_TO_FINISH_PURCHASE							=> "Unable To Finish Purchase",
		self::MARKET_OFFER_CURRENCY_MISMATCH							=> "Offer Currency Mismatch",
		self::MARKET_PAYMENT_CURRENCY_INCORRECT							=> "Payment Currency Incorrect",	
		self::MARKET_RECURRING_PAYMENT_NOT_ALLOWED						=> "Recurring Payment Not Allowed",	
		self::MARKET_PO_ALREADY_REFUNDED								=> "Po Already Refunded",
		self::MARKET_INVALID_AUTHORIZATION								=> "Invalid Authorization",
		self::CURRENCY_NOT_FOUND										=> "Currency Not Found",
		self::CURRENCY_INVALID_CURRENCY									=> "Invalid Currency",	
		self::CURRENCY_CANNOT_CREATE_OR_MODIFY_REAL_CURRENCIES			=> "Cannot Create Or Modify Real Currencies",
		self::APPMGR_CURRENCY_NOT_VISIBLE								=> "Currency Not Visible",
		self::APPMGR_APPLICATION_FAMILY_NOT_FOUND						=> "Application Family Not Found",	
		self::APPMGR_APPLICATION_FAMILY_MISMATCH						=> "Application Family Mismatch",	
		self::APPMGR_APPLICATION_NOT_FOUND								=> "Application Not Found",
		self::APPMGR_APPLICATION_MISMATCH								=> "Application Mismatch",
		self::APPMGR_APPLICATION_CHANGE									=> "Application Change",	
		self::APPMGR_APPLICATION_FAMILY_CHANGE							=> "Application Family Change",
		self::EVENT_GROUP_NOT_SET										=> "Event Group Not Set",
		self::EVENT_GROUP_NOT_FOUND										=> "Event Group Not Found",
		self::EVENT_GROUP_DUPLICATE_EXTERNAL_TRANSACTION_ID				=> "Duplicate External Transaction Id",
		self::VOUCHER_EXPIRED_VOUCHER									=> "Expired Voucher",	
		self::VOUCHER_NOT_FOUND											=> "Voucher Not Found",	
		self::VOUCHER_POLICY_NOT_FOUND									=> "Voucher Policy Not Found",
		self::VOUCHER_STATE_CHANGE										=> "Voucher State Change",
		self::VOUCHER_NOT_EFFECTIVE										=> "Voucher Not Effective",
		self::ITEM_VOUCHER_MULTIPLE_REDEMPTIONS_PER_USER				=> "Multiple Redemptions Per User",	
		self::ITEM_VOUCHER_CURRENCY_MISMATCH							=> "Voucher Currency Mismatch",
		self::ITEM_VOUCHER_TEMPLATE_NOT_FOUND							=> "Voucher Template Not Found",	
		self::ITEM_VOUCHER_TEMPLATE_NOT_AVAILABLE						=> "Voucher Template Not Available",
		self::MIDAS_ACCOUNT_NOT_FOUND									=> "Account Not Found",	
		self::MIDAS_ACCOUNT_POLICY_NOT_FOUND							=> "Account Policy Not Found",
		self::MIDAS_ACCOUNT_NOT_ACTIVE									=> "Account Not Active",
		self::MIDAS_ACCOUNT_NOT_COMPATIBLE								=> "Account Not Compatible",
		self::MIDAS_ACCOUNT_POLICY_VIOLATION							=> "Account Policy Violation",
		self::MIDAS_ACCOUNT_MAX_BALANCE_EXCEEDED						=> "Max Balance Exceeded",
		self::MIDAS_ACCOUNT_MIN_BALANCE_EXCEEDED						=> "Min Balance Exceeded",
		self::MIDAS_ACCOUNT_WITHDRAW_FROM_SINK							=> "Withdraw From Sink",
		self::MIDAS_ACCOUNT_DEPOSIT_TO_SOURCE							=> "Deposit To Source",	
		self::MIDAS_ACCOUNT_ROLE_NOT_COMPATIBLE							=> "Account Role Not Compatible",	
		self::MIDAS_ACCOUNT_INSUFFICIENT_BALANCE						=> "Insufficient Balance",
		self::MIDAS_ACCOUNT_INVALID_AMOUNT								=> "Invalid Amount",	
		self::MIDAS_ACCOUNT_INVALID_CHARGE								=> "Invalid Charge",
		self::MIDAS_ACCOUNT_MIDAS_TXN_NOT_FOUND							=> "Midas Txn Not Found",
		self::MIDAS_ACCOUNT_NEGATIVE_TRANSFER_AMOUNT					=> "Negative Transfer Amount",
		self::MIDAS_ACCOUNT_NOT_VIRTUAL_MINT							=> "Not Virtual Mint",	
		self::MIDAS_ACCOUNT_TRANSFER									=> "Transfer",	
		self::MIDAS_ACCOUNT_ZERO_TRANSFER_AMOUNT						=> "Zero Transfer Amount",
		self::MIDAS_PAYMENT_UNSUPPORTED_PAYMENT							=> "Unsupported Payment",	
		self::MIDAS_PAYMENT_PURCHASE_ORDER_NOT_FOUND					=> "Purchase Order Not Found",
		self::FOREX_BADLY_DATED_FOREX_OFFER								=> "Badly Dated Forex Offer",
		self::FOREX_OFFER_NOT_FOUND										=> "Offer Not Found",	
		self::FOREX_INVALID_PREFERRED_AMOUNTS							=> "Invalid Preferred Amounts",
		self::PAYMENT_GATEWAY_CONFIG_NOT_FOUND							=> "Payment Gateway Config Not Found",
		self::PAYMENT_GATEWAY_NOT_FOUND									=> "Payment Gateway Not Found",
		self::PAYMENT_GATEWAY_INVALID_PAYMENT_GATEWAY_OPERATION			=> "Invalid Payment Gateway Operation",
		self::PAYMENT_GATEWAY_INVALID_PAYMENT_GATEWAY_CURRENCY			=> "Invalid Payment Gateway Currency",
		self::PAYMENT_PROCESSOR											=> "Payment Processor",	
		self::PAYMENT_PROCESSOR_PAYMENT_OPTION_NOT_ENABLED_FOR_ACCOUNT	=> "Payment Option Not Enabled For Account", 		
		self::PAYMENT_PROCESSOR_UNAVAILABLE								=> "Payment Processor Unavailable",	
		self::PAYMENT_PROCESSOR_UNSUPPORTED_CURRENCY					=> "Unsupported Currency",
		self::PAYMENT_PROCESSOR_UNSUPPORTED_PAYMENT_OPTION				=> "Unsupported Payment Option",	
		self::PAYMENT_PROCESSOR_CURRENCY_NOT_ENABLED_FOR_ACCOUNT		=> "Currency Not Enabled For Account",
		self::CURRENCY_EXCHANGE											=> "Currency Exchange",	
		self::RESTRICTION_LIMIT_REACHED_USER_BLOCKED					=> "Limit Reached User Blocked",	
		self::RESTRICTION_LIMIT_REACHED_ACTION_REJECTED					=> "Limit Reached Action Rejected",	
		self::POLICY_NOT_FOUND											=> "Policy Not Found",	
		self::POLICY_COLLECTION_NOT_FOUND								=> "Policy Collection Not Found",	
		self::POLICY_COLLECTION_INCLUSIVENESS							=> "Policy Collection Inclusiveness",
		self::RECOMMENDATION_STATIC_RECOMMENDATION_NOT_FOUND			=> "Static Recommendation Not Found",
		self::PROMOTION_NOT_FOUND										=> "Promotion Not Found",
		self::PROMOTION_VALIDATION										=> "Promotion Validation",
		self::PROMOTION_CANNOT_BE_COMBINED								=> "Promotion Cannot Be Combined",	
		self::PROMOTION_NOT_COMPATIBLE_WITH_OFFER						=> "Promotion Not Compatible With Offer",	
		self::PROMOTION_WILL_CAUSE_OFFER_GO_UNDER_MIN_PRICE	 			=> "Promotion Will Cause Offer Go Under Min Price",
		self::PROMOTION_REQUIREMENT_NOT_SATISFIED						=> "Promotion Requirement Not Satisfied",	
		self::PROMOTION_JOB_NOT_FOUND									=> "Promotion Job Not Found",
		self::PROMOTION_JOB_VALIDATION									=> "Promotion Job Validation",
		self::PROMOTION_EXPIRED											=> "Promotion Expired",	
		self::PROMOTION_EXCEEDS_MAX_USES								=> "Promotion Exceeds Max Uses",	
		self::PROMOTION_USER_EXCEEDS_MAX_PROMOTION_USES					=> "User Exceeds Max Promotion Uses",
		self::PROMOTION_INELIGIBLE_USER									=> "Ineligible User",	
		self::PROMOTION_NOT_YET_EFFECTIVE								=> "Promotion Not Yet Effective",	
		self::PROMOTION_INVALID_PROMOTION_STATE							=> "Invalid Promotion State",
		self::ORGANIC_TFEL_TFE_INVALID_LOGIN_INFO						=> "TFE Invalid Login Info",
		self::ORGANIC_TFEL_TFE_ILLEGAL_ARGUMENT							=> "TFE Illegal Argument",
		self::ORGANIC_TFEL_TFE_NAMED_PARTY_NOT_FOUND					=> "TFE Named Party Not Found",
		self::ORGANIC_TFEL_TFE_ACCOUNT_NOT_FOUND						=> "TFE Account Not Found",
		self::ORGANIC_TFEL_TFE_SERVICE									=> "TFE Service",
		self::ORGANIC_TFEL_TFE_APPLICATION_PROFILE_NOT_FOUND			=> "TFE Application Profile Not Found",
		self::ORGANIC_TFEL_TFE_OFFER_TYPE_MISMATCH						=> "TFE Offer Type Mismatch",
		self::ORGANIC_TFEL_TFE_WSDL_NOT_FOUND							=> "TFE Wsdl Not Found",
		self::ORGANIC_TFEL_TFE_ENTITY_EXISTS							=> "TFE Entity Exists",	
		self::ORGANIC_TFEL_TFE_NOT_A_TWOFISH							=> "TFE Not A Twofish",	
		self::ORGANIC_TFEL_TFE_ROLLBACK									=> "TFE Rollback",	
		self::ORGANIC_TFEL_TFE_ACTOR_NOT_FOUND							=> "TFE Actor Not Found",
		self::ORGANIC_TFEL_TFE_ENTITY_NOT_FOUND							=> "TFE Entity Not Found",
		self::ORGANIC_TFEL_TFE_BATCH_TIMEOUT							=> "TFE Batch Timeout",
		self::ORGANIC_TFEL_TFE_USER_BLOCKED								=> "TFE User Blocked",

	);

	public function __construct($message = null, $code = null) {
		if (!empty($this->messages[$code])) {
			$message = $this->messages[$code];
		}
		parent::__construct($message, $code);
	}
}